[workspace]
members = ["crates/lockdocs-core", "crates/lockdocs"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/SylphxAI/lockdocs"
homepage = "https://sylphxai.github.io/lockdocs/"

[profile.release]
lto = "thin"
codegen-units = 4
strip = true
opt-level = 3
