// Editor install surfaces share the existing Claude plugin's MCP command.
// Run with --write to render, or --check (the default) to verify.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { strict as assert } from "node:assert";

const root = fileURLToPath(new URL("../", import.meta.url));
const read = (path: string) => readFileSync(resolve(root, path), "utf8");
const plugin = JSON.parse(read(".claude-plugin/plugin.json"));
const name: string = plugin.name;
const pkg = JSON.parse(read(`packages/${name}/package.json`));
const config = plugin.mcpServers[name];
assert.equal(pkg.name, `@sylphx/${name}`);
assert.ok(pkg.bin[name]);
assert.deepEqual(config, { command: "npx", args: ["-y", pkg.name, "mcp"] });
const description = name === "repomap" ? JSON.parse(read("brand.json")).oneliner : pkg.description;
const { mcpServers, ...metadata } = plugin;
const cursor = `https://cursor.com/en/install-mcp?name=${encodeURIComponent(name)}&config=${encodeURIComponent(Buffer.from(JSON.stringify(config)).toString("base64"))}`;
const vscodeConfig = { name, ...config };
const vscode = `https://insiders.vscode.dev/redirect?url=${encodeURIComponent(`vscode:mcp/install?${encodeURIComponent(JSON.stringify(vscodeConfig))}`)}`;
// Round-trip through the same decoding layers as each editor.
assert.equal(new URL(cursor).searchParams.get("name"), name);
assert.deepEqual(JSON.parse(Buffer.from(new URL(cursor).searchParams.get("config")!, "base64").toString()), config);
const inner = new URL(new URL(vscode).searchParams.get("url")!);
assert.equal(inner.protocol, "vscode:");
assert.equal(inner.pathname, "mcp/install");
assert.deepEqual(JSON.parse(decodeURIComponent(inner.search.slice(1))), vscodeConfig);

const block = `<!-- editor-install:start (generated by scripts/editor-install.ts) -->
### Cursor and VS Code, one click

[![Add to Cursor](https://cursor.com/deeplink/mcp-install-dark.svg)](${cursor}) · [Install in VS Code](${vscode})

Requires Node 18+. Confirm the install in your editor, open your project, and enable the server. Both links run \`npx -y ${pkg.name} mcp\` locally; no API key is needed.

For VS Code from a terminal:

\`\`\`bash
code --add-mcp '${JSON.stringify(vscodeConfig)}'
\`\`\`

Or add the server to \`.cursor/mcp.json\`:

\`\`\`json
${JSON.stringify({ mcpServers: { [name]: config } }, null, 2)}
\`\`\`

For \`.vscode/mcp.json\`, use the VS Code \`servers\` format:

\`\`\`json
${JSON.stringify({ servers: { [name]: { type: "stdio", ...config } } }, null, 2)}
\`\`\`
<!-- editor-install:end -->`;
const problems: string[] = [];
const write = process.argv.includes("--write");
function sync(path: string, after: string) {
  let before: string | undefined;
  try { before = read(path); } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  if (before === after) return;
  if (write) {
    mkdirSync(resolve(root, path, ".."), { recursive: true });
    writeFileSync(resolve(root, path), after);
  } else problems.push(path);
}
sync("mcp.json", JSON.stringify({ mcpServers }, null, 2) + "\n");
sync(".cursor-plugin/plugin.json", JSON.stringify({ ...metadata, description }, null, 2) + "\n");
for (const path of ["README.md", "docs/guide/quickstart.md", "docs/guide/setup.md"]) {
  const before = read(path);
  const start = "<!-- editor-install:start (generated by scripts/editor-install.ts) -->";
  const end = "<!-- editor-install:end -->";
  const a = before.indexOf(start), b = before.indexOf(end);
  assert.ok(a >= 0 && b > a, `${path}: editor install markers missing`);
  sync(path, before.slice(0, a) + block + before.slice(b + end.length));
}
if (problems.length) throw new Error(`Editor install surfaces out of date: ${problems.join(", ")}. Run bun scripts/editor-install.ts --write`);
console.log(`Editor install manifests and deep links ${write ? "synced" : "verified"}`);
